name: cascade_picker
description: 级联选择器
version: 0.0.7
homepage: https://github.com/xionghaoo/cascade_picker

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
